discordClientId : 1111111111111111111
discordClientSecret : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
discordBotToken : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
discordRedirectUriPort : 8000
checkForGuildsOnJoin : []
syncDiscordRolesOnJoin : []
allowMultipleMinecraftAccountsPerDiscordAccount : false
mandatoryVCChannels : []
banDiscordAccount : true